### ISSUE TITLE
Unable to use Android Phone as Security Key

### ISSUE THREAD

**Issue by aksha78** [StrongKey/fido2#111]
Dear Strongkey Support,

We are successfully able to deploy Strongkey FIDO Open source server. Also we deployed sample java web application (https://github.com/strong
key/fido2/tree/master/sampleapps/java/poc/).

On visiting "https://njauth.nj:8181/basicserver/", we are able to view only 3 options (Bluetooth,USB and NFC). I am using Android (10) with chrome browser, however I am not able to use fingerprint/pin. Basically I am not able to use Android phone as a security key. Please find attached video as well and server details as below :

[root@njauth skfsclient]# java -jar skfsclient.jar P https://njauth.nj:8181 1 REST HMAC 162a5684336fa6e7 7edd81de1baab6ebcc76ebe3e38f41f4

Copyright (c) 2001-2021 StrongAuth, Inc. All rights reserved.

REST Ping test with HMAC
******************************************
json = {"svcinfo":{"did":1,"protocol":"FIDO2_0","authtype":"HMAC"},"payload":""}

Calling ping @ https://njauth.nj:8181/skfs/rest/ping

Ping test complete.
******************************************
Ping response : StrongKey, Inc. FIDO Server 4.4.0
Hostname: njauth.nj (ServerID: 1)
Current time: Tue Apr 27 18:12:08 IST 2021
Up since: Tue Apr 27 17:12:06 IST 2021
FIDO Server Domain 1 is alive!

Done with Ping!

Regards
Aksha

https://user-images.githubusercontent.com/83274190/116248435-804fbe80-a789-11eb-9e83-c8295f78b0d8.mp4

**Comment by arshadnoor** [comment]
Aksha,

Here are a few things you should check:

1) Do you have a fingerprint registered?
2) Have you setup lock screen and your fingerprint to unlock the device?
3) Are you using a current release of Chrome (v90)?
4) Have you tested your mobile + browser with 
https://demo4.strongkey.com/basicserver

I just tested my 3 year old Essential PH-1 with Android 10 on the Basic 
Server demo and it was able to register and authenticate with my 
fingerprint.

If your mobile works with the Basic demo on strongkey.com, download and 
install that demo on your FIDO server and see if that works. Let us know 
the results.

**Comment by aksha78** [comment]
Hi Arshad,

Thank you for your prompt response. Unfortunately, I missed out on the important point (point 1 mentioned by you). The fingerprint was not registered and hence I was not able to view that option during the registration flow. This is now working for me.

Currently, I am testing the functionality on iphone11+chrome and Windows10+hello+chrome also. I am facing some challenges. Will this also work on iphone11+chrome and Windows10+hello+chrome?

Regards,
Aksha.

**Comment by arshadnoor** [comment]
On iPhones, you must always use Safari to use FIDO. On Windows 10, you 
must use Edge.

Remember, Firefox, Chrome, Opera and Brave work with almost all external 
Security Keys. If you want to use a platform authenticator - such as a 
secure element or a TPM built-into the device, you should use the native 
browser for that platform: Chrome for Android, Safari for iOS/OS-X and 
Edge for Windows 10.

**Comment by aksha78** [comment]
Hi Arshad,

This is working great in iphone+safari and Windows+hello+chrome as well.

Request you to help me understand, how will this work in non supported platforms like Linux (ubuntu) workstations? Do we always require Windows Help in Windows OS?

Can we use Mobile devices as biometric-enabled roaming authenticators for web applications? How will desktop/laptop communicate with Mobile Phone Devices? Using USB Keys/NFC etc is not a feasible option if we want this to work for a larger group of our customers.

Is BLE the only option available? Do we have any demo to have hands-on experience of laptop communicating with Mobile Phone for registration and authentication?

For a few demos I saw, some are using push notifications, QR codes, etc.

I also saw few posts on google doing some work on caBLE. (https://bugs.chromium.org/p/chromium/issues/detail?id=1002262&q=component%3ABlink%3EWebAuthentication). Is StrongKey Open Source FIDO server compatible with this? We tried by enabling chrome://flag (#enable-web-authentication-cable-v2-support) on laptop and on mobile phone (Use Phone as security key) as well but this it is not working.

The simple Use case (authentication) we would like to achieve is -

1) User visits example.com from a browser on laptop/desktop
2) User receives a notification on phone to authenticate.
2) User scans a QR code from mobile phone displayed on a web browser on laptop/desktop  
3) User provides biometric authentication on Mobile Phone
4) User gets authenticated on web application example.com on Laptop

Regards,
Aksha

**Comment by aksha78** [comment]
Arshad,

To make things clear I am thinking about the use-case mentioned below - 

https://w3c.github.io/webauthn/#sctn-usecase-authentication

Thanks and Regards,
Aksha

**Comment by arshadnoor** [comment]
I'm glad that things are working for you now with iPhones and Windows. 
Its interesting that Chrome also works on Windows, but I'm not surprised 
that Chrome is leveraging the same DLLs that Microsoft is using with 
Edge to use the TPM for FIDO2 credentials.

For Linux, someone is going to have to create an open-source library 
that binds the TSS (software library that interacts with a TPM) and the 
CTAP2 protocol that browsers use to talk to FIDO Authenticators.

Right now, FIDO Alliance says that BLE and NFC are the ways in which a 
desktop/laptop session can communicate with an "external" device - such 
as a mobile - to strongly authenticate a user. There are even demos that 
Microsoft and Google have showed in the past; but I agree that I haven't 
seen anything in production quality yet. I think it has to do more with 
the fact that Chrome - which must support the NFC/BLE protocols to talk 
to FIDO Authenticators - is on a different schedule than the team that 
focuses on FIDO protocols; so, congruence is not achieved yet.

In the meantime, while it will be possible to authenticate 
desktop/laptop sessions on a mobile using other mechanisms - QR codes, 
for example - you have to be careful to not leave vulnerability gaps in 
a "disassociated" authentication flow, because the gap can allow an 
attacker to get in the middle of that flow.

When I say "disassociated", I mean that the user is using one flow on 
their desktop that leads to a QR code, while reading that QR code by an 
app on a mobile and resolving that code into a series of actions that 
allow the user to be authenticated on the desktop is a different flow. 
Given all the moving parts in the second flow and the back-end processes 
that must happen to tie the second flow to the first one, there could be 
many points of attack that leads to a compromise.

This is not to say that BLE/NFC also cannot be compromised - I don't 
know enough about those protocols to be able to say definitively - but 
these are the types of issues one must consider when mitigating risk.

Hope that helps.
