### ISSUE TITLE
Pass code not received on Phone - Demo App

### ISSUE THREAD

**Issue by mani516** [StrongKey/fido2#142]
Hi There!

I am not able to signup into https://demo5.strongkey.com/ as pass code is not received. (Indian number)

**Comment by pattycakelol** [comment]
Hi @mani516,

I have checked the SMS Provider's logs and it seems that the OTP has been sent. You may want to ensure that your network provider is not blocking these messages.

**Comment by mani516** [comment]
Hey @pattycakelol 

I have never faced any issue with receiving codes over my phone number. Is there any chance that the possible blocking by my network provider is related to the sms provider being used?

Also why is mobile number required? That too with verification?

**Comment by pattycakelol** [comment]
Hi @mani516,

The service we use is Nexmo and it is possible that sms sent by this service being blocked by your network provider.
We use mobile number to recover accounts when a user has lost their security keys and cannot access their account; only an administrator can access this.

**Comment by pattycakelol** [comment]
Hi @mani516,

I am looking at the database and I see that the last OTP you attempted to use is still valid for another 12 hours. I will email it to you privately. You should be able to use the same registration link that you were emailed before.

Otherwise, if you are trying a new registration, please comment in this thread when you reach the step that needs the OTP and we will send it to you privately.
