### ISSUE TITLE
Passing the conformance tools

### ISSUE THREAD

**Issue by herrjemand** [StrongKey/fido2#15]
Have you guys though of passing conformance tests? https://fidoalliance.org/certification/functional-certification/conformance/

**Comment by push2085** [comment]
Hi @herrjemand ,
We have passed all the conformance tests when we got our FIDO 2 server certified back in February. I believe there may be new tests added to that test tool, so we would continue to test against it.

I will update our repository home page with the FIDO Certified Logo so that its is evident that we have gone through the certification process.

**Comment by herrjemand** [comment]
Has this POC been certified?

**Comment by arshadnoor** [comment]
Hi Yuri,

As you know, only the FIDO2 server can be certified by the FIDO Alliance.  The PoC web-application is merely an RP web-application to demonstrate how to use the our FIDO2 server, as well as to introduce an important concept that the vast majority of neophytes to the FIDO world do not grasp: that a user can have multiple keys registered to a single account.  This is an important distinction between FIDO and every other authentication technology that preceded it.  (While it was possible with X.509 certificates too, no PKI I know, to the best of my knowledge, ever issued multiple signing certificates to an end-entity that would allow them to authenticate to a TLS site with multiple certificates - end-entities were always issued a single digital certificate).

Our goal at StrongKey is to not just build a great open-source FIDO2 server (lots more capability coming in the future), but to show developers multiple applications using FIDO2 in multiple programming languages so that they understand it in their own language.  We hope to make it a "Central Station" for a wide variety of FIDO2-enabled web and mobile applications that people can share and download - the only requirement is that the app use our FIDO2 server in their demonstration.
