### ISSUE TITLE
Is possible FIDO server run on Apache Tomcat ?

### ISSUE THREAD

**Issue by prathapcoder** [StrongKey/fido2#181]
My firewall blocking Payara server due to security issues. In Payara server some libraries have *security vulnerabilities* becuase of this problem my firewall blocking. So that i want to use *Tomcat server insted of Payara server*. 
**Is there possiblity FIDO server run on Apache Tomcat?**
Thank you.

**Comment by pattycakelol** [comment]
Hi @prathapcoder,
While we have not tested it, Apache Tomcat should be able to run the SKFS. Since the FIDO Server is nothing more than a deployable ear file, any web server that supports JEE should be able to run the SKFS on top of it. However, you may need to change some Tomcat configurations to match those made in Payara at install time and manually set some SKFS properties for the SKFS to function properly.

**Comment by pattycakelol** [comment]
Another approach that may be worth tackling is changing the Payara `wget` command to download a more recent version of Payara (at the moment, we support Payara 5.2020.7). [Here](https://repo1.maven.org/maven2/fish/payara/distributions/payara/) is a list of Payara versions you may choose from.
