### ISSUE TITLE
For Fido2 Developer Team

### ISSUE THREAD

**Issue by Saebyeol98** [StrongKey/fido2#219]
Hello Strongkey Developer Team.
I am going to make an Android-based FIDO2 certification app with SKFS.
I am contacting you because I have a question while studying your source code.
Among the samples included in the project, I would like to develop my project using the code of the Android part.
I saw that the example project was also applied to LGPL 2.1.
Then, after I make my project, If I use this SACL Library project file in my private repository, should I open it to GitHub as a open source?

I think I will modify a part of the SACL Library code.
The parts that need to be modified in the SACL library within the project are as follows :
- URL required for communication
- CRT certificate required for communication
- modification of some source code
I look forward to your reply.
Thanks.

**Comment by arshadnoor** [comment]
@Saebyeol98  Since all our software on Github is open-source, you can modify it and redistribute it. The only requirement is that your own software must be distributed as open-source too. You must maintain our copyright statement in every file as-is, but you can add your own comments to the modifications you make. You can also choose to store your project in your own repository within Github and reference our project in your documentation.

The only thing you cannot do is make modifications to our source code and distribute the result as a close-source app with your own copyrights. However, with a support contract from us, you can choose to distribute such an app if you wish, but that app must distribute your code as open-source if your code references our open-source code.

Hope that helps.

**Comment by Saebyeol98** [comment]
@arshadnoor 
Thank you for your reply.
Then, additionally You Says, "The only requirement is that your own software must be distributed as open-source too."
I wonder if the scope of the original software is a project that modified strongkey or the entire project of our company linked to strongkey

**Comment by arshadnoor** [comment]
If you want a quick answer, here it is: https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

If you want a more detailed answer, you should have your attorney read this: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
