### ISSUE TITLE
How to use the api calls

### ISSUE THREAD

**Issue by techfreak748** [StrongKey/fido2#32]
Hello again,
I am trying to use the api calls to create an android app that communicates with the server, but i cannot understand how to use the parameters hmac or sha to authenticate  to server.
Any help please?

**Comment by DavidCBeach** [comment]
Hello,
HMAC parameter is a header parameter whose content is an HMAC encoded value that is used to verify the senders identity and validate the contents of the request. The data that is encoded in the HMAC includes the request method, a hash of the body content, the content type, the current date, the API version, and the request URL. This HMAC is calculated using the FIDO2 Server's secret key. The resulting HMAC is added to the header as the value of the "Authorization" parameter in the format: 'HMAC [ACCESSKEY]:[HMAC]' with [ACCESSKEY] being the access key of the FIDO2 Server and [HMAC] being your HMAC value. 
The body hash is also added to the headers as the value of "strongkey-content-sha256"

I am willing to answer anymore questions you might have in regards to implementing this authentication method if your project is under a time constraint. However, if you are able to wait a week, we are planning on releasing the next version of our FIDO2 Server that will have a simple username and password method to authenticate to the server. Upon the release, I am willing to send you a document that outlines the api call structures. Please tell me if this works for you.

**Comment by techfreak748** [comment]
@DavidCBeach Thank you very much for your response. Of course it would be helpfull to send me the document that outlines the api calls. More specifically i would like create a fido2 android client that uses these calls. I wanted to also ask, is the Poc web app considered a client?

**Comment by DavidCBeach** [comment]
@techfreak748 
First, the latest version of our FIDO2 Server is currently up. There is instructions on how to upgrade your FIDO2 Server so that you can take advantage of the username/password server authentication method.
https://github.com/StrongKey/fido2/blob/master/docs/Upgrade_Guide_Linux.md

Second, yes the POC is a good example of how implement with our FIDO2 Server. Specifically https://github.com/StrongKey/fido2/blob/master/sampleapps/java/poc/server/src/main/java/com/strongkey/poc/SKFSClient.java 
This file is where the POC server makes API calls to the FIDO2 Server. 
If you look at 'callSKFSRestApi' method you will see an example of the username and password implementation of server authentication. 
Please be advised that there are other API call changes from the old version of our FIDO2 Server to the current version 
Hope this helps.

**Comment by techfreak748** [comment]
@DavidCBeach  Thank you very much this helps a lot. So practically the whole installation is a client - server infrastucture right?

**Comment by techfreak748** [comment]
@DavidCBeach  Mr Beach sorry for spamming, but i got some questions. Poc is the client and fido2 server is the server side right? They also communicate through api calls if i understand correctly.
When i try to use postman to send a request using the api calls and this endpoint https://fqdn:8181/skfs/rest/ping i get a 404 error. Why is this happening? I mean how can i find the endpoints to call?
Thanks in advance and sorry again

**Comment by vamseeganti** [comment]
@DavidCBeach I have similar problem as @techfreak748. I was trying to call <ip>:8181/api/domains/fidokeys but I get a 404, probably because the **getKeys** method URL doesn't have did in it?. 

The **getKeys** method is calling **callSKFSRestApi**. But all that method seems to be doing is making a POST call all the time, even for GET requests. 

I tried username and password authn but I have similar problems with HMAC authentication as well.

I've been struggling to make the API calls from Postman for the last two weeks. Any help is greatly appreciated. 

I added my Postman collection for your reference.
[FIDO.postman_collection.zip](https://github.com/StrongKey/fido2/files/4258885/FIDO.postman_collection.zip)

**Comment by DavidCBeach** [comment]
@techfreak748 @vamseeganti  Here is where you can find the API documentation: https://strongkey.github.io/fido2/#/

@techfreak748 First, The POC is a web application and an application server. The POC server calls the FIDO2 Server like, according to my understanding, what you want your android application to. The idea behind having our stand alone FIDO2 Server is that it handles the FIDO2 functionality so that you only have to make simple API calls from whatever application you are developing. In the case of the POC, it is supposed to act as an example of how a website with its own frontend and backend can implement our FIDO2 Server to manage its FIDO2 functionality. 

Second, your API call has the correct path so you shouldn't be getting a 404 response. My assumption is the problem must be somewhere else. Please make sure port 8181 is open on your FIDO2 Server. Also, make sure you are able to access your FIDO2 Server from your testing device by going to https://fqdn:8181 in a browser.  

@vamseeganti For your issue please see the API document.

**Comment by techfreak748** [comment]
Mr @DavidCBeach,
I reinstalled the latest server and poc version. When i try to make the ping call i get error 415 unsupported media type. I really cannot figure out how to make it work. Ideally i would like to create a simple client, but if the poc is considered the client lets say side then im fine with that.

**Comment by DavidCBeach** [comment]
@techfreak748 Does your request header contain 'Content-Type' set to 'application/json'?
If not, please add this header to your request.

**Comment by techfreak748** [comment]
Yes but what to include in it? I have a registered user who registered by fingerprint.

**Comment by DavidCBeach** [comment]
@techfreak748 So are you saying that you have been able to successfully make other API calls to the FIDO2 Server? 
Are you only having problems with the ping call or all the requests?

**Comment by techfreak748** [comment]
No i mentioned it as an example

**Comment by DavidCBeach** [comment]
@techfreak748 
Here is the flow for registering a new user:
1. The user inputs their username and display name (display name is used to identify their FIDO2 authenticator ex. the device with the fingerprint reader)
2. username and display name are sent to the FIDO2 Server via post request to https://fqdn:8181/skfs/rest/preregister
3. FIDO2 Server sends a challenge as a response to the post request
4. Convert the challenge from Base64 to Buffer
5. Run a "create" call to the FIDO2 Authenticator (This can be done in JavaScript running in a supported web browser by running window.navigator.credentials.create({ publicKey: challengeBuffer }) | the create call will be different in Android)  
6. The FIDO2 Authenticator will return a response. 
6. Convert the response from the FIDO2 Authenticator from a Buffer to Base64
7. Send the Base64 response to the FIDO2 Server via post request https://fqdn:8181/skfs/rest/register
8. The user is now registered. 

For detail on the format the requests please refer to the API document.

**Comment by techfreak748** [comment]
@DavidCBeach so basically Poc could also be considered as a client right? Since it is an application server which runs a web app right?
So Fido2 server and Poc app server could be considered as a client - server infrastructure right?

**Comment by techfreak748** [comment]
I am trying to make the preauthenticate api call using this end point: https://fqdn:8181/skfs/rest/preauthenticate and using this json: {
  "svcinfo": {
    "did": 1,
    "protocol": "FIDO2_0",
    "authtype": "PASSWORD",
    "svcusername": "svcfidouser",
    "svcpassword": "Abcd1234!"
  },
  "payload": {
    "username": "username",
    "options": "{}"
  }
}


But i get the error : FIDO-ERR-0003: Error during preregister: {0}SKCEWS-ERR-3055: Invalid user: svcfidouser.
Any suggestions?

**Comment by pattycakelol** [comment]
Hi @techfreak748 ,
Here is a postman collection for the StrongKey FIDO2 Server that I have made and tested that it works.
[SKFS_REST_PASSWORD_AUTH.zip](https://github.com/StrongKey/fido2/files/4277120/SKFS_REST_PASSWORD_AUTH.zip)
Make sure to change the request URL when you are using it.

Could you both of the following:
1. Tail the glassfish server logs and post the output from making a postman request using the above postman collection
2. Tail the OpenDJ logs and post the output from making a postman request using the above postman collection

**Comment by techfreak748** [comment]
I had similar logs with nikosf95 on this issue https://github.com/StrongKey/fido2/issues/38.
I also saw in this comment that there is a client programm and i wanted to ask how can it be used as a standalone client to make fido2 api calls.

**Comment by DavidCBeach** [comment]
@techfreak748 
Here is the Documentation on the SKFSClient: https://github.com/StrongKey/fido2/blob/master/server/skfsclient/skfsclient.md
The purpose of the SKFSClient is to act a tool to test the functionality of the FIDO2 Server. It uses a simulated FIDO2 Authenticator to successfully run registration and authentication actions against the FIDO2 Server.

**Comment by techfreak748** [comment]
@DavidCBeach Perfect but how can i find the svcusername and svcpass to use in postman json requests? I can't figure out how to find out which are the default values and thus i am getting an error about invalid username

**Comment by pattycakelol** [comment]
Hi @techfreak748,
Did you happen to see any errors during your installation of the FIDO2 Server regarding OpenDJ?
The FIDO2 Server's install script includes the adding of default OpenDJ users (svcfidouser being one of them). To verify this, could you make sure that svcfidouser can be found in your "skce.ldif" in the directory where you extracted the "fido2server-v4.3.0-dist.tgz"
