### ISSUE TITLE
I want to know the role of the replicationEJB.jar file.

### ISSUE THREAD

**Issue by superbly** [StrongKey/fido2#66]
Hello

I have some questions, so I'm leaving an issue.

I want to know what the replicationEJB.jar file does in FIDO2 SERVER and the role of the replication table in skfs db.

Oh, and what is the full name of SKCE?

I'll be waiting for an answer.

**Comment by arshadnoor** [comment]
The StrongKey FIDO2 server is capable of being installed as a cluster with multiple nodes, to support high-availability (HA) and disaster recovery (DR). Within a cluster, when a user registers their FIDO2 key on one node, it is immediately replicated to all other nodes of the cluster.  Now, the user can be authenticated on any node of the cluster. The advantage of this architecture is that applications don't have to worry about availability and performance. 

The replication capability is built into the core server because we use it for all the other modules that we deploy on our Tellaro appliance (check out our website for all the other features we support on the appliance). By enabling replication in our software rather than relying on database replication, we are able to control the replication features ourselves.

An enterprise could create a FIDO2 infrastructure consisting of 2 nodes in the primary data center, and 2 nodes in the disaster recovery data center, and as long as the network between the 4 nodes is available, they will all replicate to each other. Even if a node fails, all the others will hold their objects for the missing node; when the missing node comes back, they will automatically synchronize with each other. 

The architecture also allows all nodes to work in active-active mode. This enables dozens of web-applications to use any node for registration and authentication without having to worry about HA/DR issues. The only requirement is that there must be a network path between cluster nodes and ports 7001-7003 must be opened up between just  the nodes for the replication to work. The installation process takes care of that, but if you change IP addresses, then you'll have to update the firewall rules manually.

**Comment by superbly** [comment]
thank you
