### ISSUE TITLE
Basic Java Sample Application errors

### ISSUE THREAD

**Issue by naya0823** [StrongKey/fido2#69]
Hi everyone,

I'm trying to set up the StrongKey FIDO2 Server.
I installed the server and Basic Java Sample Application with no error.

But I'm afraid I can't run a register test, and I don't know how to fix it.
Please refer to the below screenshot and server's logs,
and kindly help me to run the tests.

![스크린샷 2020-09-01 오후 5 16 53](https://user-images.githubusercontent.com/70570514/91826131-20dff400-ec78-11ea-9b83-20a1d58e7686.png)
[server.log](https://github.com/StrongKey/fido2/files/5154852/server.log)

I can't find anymore guide for this.

Thanks in advance.

**Comment by push2085** [comment]
Hi @naya0823,
We will look into this issue and get back to you but meanwhile, do you still have install logs? If so can you share those as well.
Also share with us the contents of "/usr/local/strongkey/skfs/keystores/" folder.

Thank you

**Comment by naya0823** [comment]
Hi @push2085 

I'm afraid I can't find my install logs. Where is it normally located?
Here's my full server logs yesterday. I hope it'll help.
[server_2020-09-01T23-59-46.log](https://github.com/StrongKey/fido2/files/5159934/server_2020-09-01T23-59-46.log)

There are two files in the folder 'usr/local/strongkey/skfs/keystores/'. Here's my keystore files.
[keystores.zip](https://github.com/StrongKey/fido2/files/5159937/keystores.zip)

Thank you so much.

**Comment by pattycakelol** [comment]
Hi @naya0823 

To get a general idea of what may be the cause of the problem, could you do the following:
1. Run 'df -h' and provide the output
2. Provide the contents of the server's /var/log/messages that the fido server was installed on

Taking a look at your keystores, I noticed the sha256sum of your signingkeystore.bcfks and signingtruststore.bcfks were different from the default. Because of this, I assume you used the keymanager.jar to add a new access and secret key pair to the keystore. If this is the case, you could try either of the following:
1. Try the default keys

Switch the signingkeystore.bcfks and signingtruststore.bcfks found in /usr/local/strongkey/skfs/keystores folder with the default .bcfks files, restart glassfish, and try your registration again.

2. Use your keys with the server

When a new access/secret key pair are created using the keymanager.jar tool, you get an output similar to this (dummy values used for this example):
```
Created new access/secret key:
Access key:48baaf78a4fe8847
Secret key:915f77b9389ca75f47624f497993810c
```
Using these keys, you may add the following to your webauthntutorial-configuration.properties located in /usr/local/strongkey/webauthntutorial/etc on the server the basic java sample application was installed:
```
webauthntutorial.cfg.property.accesskey=48baaf78a4fe8847
webauthntutorial.cfg.property.secretkey=915f77b9389ca75f47624f497993810c
```
After adding these properties, restart glassfish and try your registration again.

The use of the keymanager.jar tool and how it interacts with the sample applications will be made more clear in the instructions.
I hope to hear from you soon.

**Comment by naya0823** [comment]
Hi @pattycakelol 

Thank you for your advices.

Here's my 'df -h' output and '/var/log/messages'.
[df_result.log](https://github.com/StrongKey/fido2/files/5167301/df_result.log)
[messages.txt](https://github.com/StrongKey/fido2/files/5167303/messages.txt)
(I installed the server around 12pm September 2nd)

also tried again with the default keys.
[defaultkeys.zip](https://github.com/StrongKey/fido2/files/5167325/defaultkeys.zip)

And then I got HMAC authentication failed. Please refer to the follow 'server.log'.
[server.log](https://github.com/StrongKey/fido2/files/5167315/server.log)


Please show me the way to fix it. :(

Thank you.

**Comment by pattycakelol** [comment]
Hi @naya0823 

There are a lot of things that go into the calculation of the HMAC, so it is hard to determine which is the issue if the HMAC does not match.
If you have not already installed this using CentOS, I would recommend trying a fresh reinstall of the FIDO2 Server and Basice Java Sample Application on a CentOS vm with all default values just to make sure it can work.
Let me know how that goes.

**Comment by naya0823** [comment]
Hi @pattycakelol 

I tried the fresh reinstall but it's still not working.

So I changed authtype 'HMAC' to 'PASSWORD' through changing configurations.
Finally it works!!!!

Thank you so much for the advices.
