### ISSUE TITLE
Resident key support

### ISSUE THREAD

**Issue by GramThanos** [StrongKey/fido2#72]
Is there any way to request from the server an authentication using resident key without providing a username through the [FIDO2 Server API](https://strongkey.github.io/fido2/)?

It seems that the username parameter is always needed.

**Comment by max-smyth** [comment]
Hi Grammatopoulos,

Once a user has registered a FIDO2 key (or authenticated from a 
computer/device they've used to access your site), you can always set a 
cookie to store the FIDO2 username and pick up that cookie each time the 
user authenticates from the same computer/device. The only time they 
will need to type in a username is if they attempt to authenticate from 
a computer they've not used before.

Alternatively, you will need to extract a fair amount of extraneous 
information from the user's platform and store a unique "fingerprint" of 
that platform in association with the user's credentialId/public-key, so 
you can detect that "fingerprint" each time someone comes to your site. 
This process, however, is not definitive and could consume a fair amount 
of resources on your side.

The W3C WebAuthn spec is evolving and a Level 2 API is expected to be 
finalized later this year or early next year. It is conceivable that the 
API will provide for mechanisms to make it possible to discover resident 
keys without violating a user's security/privacy. For now, setting a 
cookie is likely the most definitive mechanism.

Hope that helps.

Arshad Noor
StrongKey

**Comment by GramThanos** [comment]
Thank you for the reply! So resident keys are not supported for privacy reasons and hopefully these will be solved at a later version of the WebAuthn.

**Comment by GramThanos** [comment]
Dear Arshad,

After inspecting once again the WebAuthn credentials get responses to resident keys requests, I don't see any difference on the responses that between u2f keys responses and resident keys responses that may raise privacy concerns.

My understanding is that the only difference is that on the resident keys case, the server do not have to return any public key on the preauthentication phase and then the authenticator will provide the user_id of the user as defined during registration.

Inplementation wise, the only difference I see is to allow preauthentication requests without a username specified (thus have challenges not related to a user) and then on authentication response retrieve the username from the authenticator response.

Am I missing something?

**Comment by max-smyth** [comment]
Hi Grammatopoulos,

I'm not sure if you're referring to FIDO2 protocols in general or to our 
implementation specifically.

What I can tell you is that our early implementation (what is on Github 
currently) does NOT deal with Resident differently from Roaming keys. 
But, our next major implementation is likely to do so for a variety of 
reasons.

In our current implementation, regardless of whether the platform is 
dealing with a Resident or Roaming Authenticator, our FIDO server DOES 
return previously registered public-keys (f any) to a PreAuth request.

Some RPs have stated that they don't want that for Resident keys because 
it leaks information to attackers. If an RP's policy is to ONLY require 
Resident keys, for example, then there is no reason to return 
public-keys (or Key Handles) - just the submission of the userid from 
the platform should be sufficient for the FIDO Server and the 
Authenticator to identify the keys they need to work with on that 
specific platform. If everybody has built their implementation 
correctly, there should be only ONE Resident key on that platform for 
that RP; and if that platform's Resident key does NOT match the userid 
sent in the PreAuth request, the platform Authenticator should NOT sign 
the challenge.

We have not seen security policies in effect in the FIDO world so far - 
at least not as much as we are used to in legacy authentication 
protocols. However, as more people are getting familiar with FIDO, and 
as more RPs understand it and make demands, the protocols will evolve to 
offer more capability - and complexity.

But, you can be assured, we are in it for the long journey.

Arshad

**Comment by GramThanos** [comment]
To make things clear, I was referring to the latest StrongKey FIDO2 server (fido2server-v4.3.0-dist.tgz) installed following the installation guide and interacting with the server only using the [FIDO2 Server API v3.0.0](https://strongkey.github.io/fido2/).
