### ISSUE TITLE
hello, i need help..

### ISSUE THREAD

**Issue by Hwang-lab** [StrongKey/fido2#95]
hello, i need  help..

I am a student studying fido.

1, i cant login in your demo web.
https://fido2.strongkey.com/#/login
I entered my mobile phone number, but an error occurred.
I choose the region as KR
I typed it like this. 
82010********
8210********
010********

2. I don't know the file structure.
If there is any structure diagram, please.

**Comment by arshadnoor** [comment]
Hi Hwang,

It appears that fido2.strongkey.com is not currently working. Please try 
using demo4.strongkey.com, demo5.strongkey.com or psd2demo.strongkey.com.

When typing in your mobile, you do NOT need to type your country code - 
so you do NOT need to type in 82. But, if you simply want to test FIDO 
on our site, you can try psd2demo.strongkey.com - it does not ask for a 
mobile number; it only asks for your e-mail address.

The advantage of testing on psd2demo is that you will also see our new 
SSO technology at work when you select My Profile - it authenticates you 
to a different web application using the signed JWT in your browser header.

Hope that helps.

**Comment by Hwang-lab** [comment]
Thank you for replying quickly. 
First of all, you cannot enter the site you sent. My screen says that I can't connect to the site. We will send you a screen capture.
demo4.strongkey.com, demo5.strongkey.com or psd2demo.strongkey.com.
Please confirm. :)
 
 
-----Original Message-----

**Comment by arshadnoor** [comment]
Hi Hwang,

You should use https:// in front of the fully qualified domain names.

Arshad

**Comment by Hwang-lab** [comment]
Thanks for the kind answer. 
As you said, I logged in well and connected well. > https://psd2demo.strongkey.com
But I don't know how to use it. I don't know if I couldn't find it, but if you have instructions or documentation, please let me know.
Thank you.

**Comment by arshadnoor** [comment]
If you have a FIDO Authenticator - such as a Windows 10 PC with Windows 
Hello configured (Edge), a MacBook Pro with TouchID (Chrome), a recent 
iPhone with an updated iOS (Safari) or an Android phone with Pie (9) or 
greater (Chrome) - then use the browser I've indicated in parentheses 
(brackets), select the "Sign Up" button, supply your e-mail address and 
select "Invite Me".

When you get the e-mail (on the same device you are using to register 
your FIDO key), select the link making sure that the link uses the same 
version of browser as shown in the brackets above for your operating 
system on the device.

This will lead you to a screen to supply some basic user information, 
and will prompt you to register a FIDO key. At this point, depending on 
your device and operating system, do one of the following:

Windows 10: PIN, password or fingerprint
MacBook: Fingerprint
iPhone: TouchID or FaceID
Android: PIN, Pattern or fingerprint

Accept the prompt that shows up and this should register a FIDO key with 
the site. This will show you a screen with some sample transactions 
created by the Android mobile app.

To see a demo of SSO, select your username on the screen, and select "My 
Profile". This will open another tab and take you to a different webapp 
(without an authentication) and show you a list of your registered FIDO 
keys.

If you have an external Security Key, you can register it here at this 
time to see how FIDO allows you to register multiple devices to the same 
account. You can then log out of both applications, and use either the 
Security Key or the original device you used to authenticate to the site.

Source code for all these webapps and the Android app are available on 
the Github repo.

**Comment by Hwang-lab** [comment]
Hello, I am a student studying FIDO. While viewing github FIDO, I have a question and ask a question.
 
fido2/server/skfsclient/src/main/java/com/strongkey/skfsclient/impl/rest/RestFidoActionsOnKey.java / 
 
https://github.com/StrongKey/fido2/blob/bad4db1108c21f7cb40c03c195d6008664f5f34d/server/skfsclient/src/main/java/com/strongkey/skfsclient/impl/rest/RestFidoActionsOnKey.java#L284
 
 public static void update(String hostport,
                            int did,
                            String authtype,
                            String credential1,
                            String credential2,
                            String keyid,
                            String displayname,
                            String status) throws Exception
 
I wonder what the purpose of displayname is.
Is it a different purpose than the <public static void updateUsername> in the middle?
 
and I wonder what <public static void update> updates

**Comment by DavidCBeach** [comment]
@Hwang-lab 

The purpose of updateKeyInfo API call  (the API endpoint called in update) is to either update the credential's display name and/or update the credential's status (Active or Inactive) for a specific credential.
The purpose of updateusername API call (the API endpoint called in updateUsername) is to update the username for all stored credentials that are associated with that username. 

The display name is different than the username. The display name in FIDO2 is a human readable ID that identifies to the user which credential (and therefor which authenticator) is being referenced. Since a user can have more than one authenticator registered with the same account (same username) they are not equivalent.   

I see that you are looking though the code for the skfsclient. The skfsclient is not meant to act as a demonstration for learning how to understand and implement FIDO2. The skfsclient uses a simulated authenticator which is irregular for actual FIDO2 implementation. If you are trying to learn FIDO2 I would suggest looking at one of our sample applications or our tutorial:

https://github.com/StrongKey/fido2/tree/master/sampleapps/java/basic
https://github.com/StrongKey/fido2/tree/master/tutorial
